#!/usr/bin/env ruby
# -*- encoding : utf-8 -*-

require 'bundler'
Bundler.setup
require File.expand_path('../../lib/rabbit_jobs', __FILE__)

class MyCurrentJob
  include RJ::Job
  def self.perform(count)
  end
end

RJ.configure { |c|
  c.queue "failover_test"
  c.server "amqp://localhost/bunny"
}

i = 0
loop do
  puts "publishing job #{i}"
  begin
    RJ.publish_to(:failover_test, MyCurrentJob, i)
  rescue Exception => e
    RJ::Publisher.amqp_connection.stop
    puts e.message
    puts e.backtrace.join("\r\n")
  end
  i += 1
  sleep 1
end
