#!/usr/bin/env ruby
# -*- encoding : utf-8 -*-

require 'bundler'
Bundler.setup
require File.expand_path('../../lib/rabbit_jobs', __FILE__)

class MyCurrentJob
  include RJ::Job
  def self.perform(count)
  end
end

RJ.configure { |c|
  c.queue "failover_test"
  c.server "amqp://localhost/"
}

RJ.logger = Logger.new($stdout)

RJ.publish_to(:failover_test, MyCurrentJob)
