#!/usr/bin/env ruby
# -*- encoding : utf-8 -*-

require 'bundler'
Bundler.setup
require File.expand_path('../../lib/rabbit_jobs', __FILE__)

class MyCurrentJob
  include RJ::Job
  queue :failover_test
  def perform(count)
  end
end

RJ.configure { |c|
  c.queue "failover_test"
  c.server "amqp://localhost/rj"
}

i = 0
loop do
  puts "publishing job #{i}"
  begin
    # RJ.publish_to(:failover_test, MyCurrentJob, i)
    MyCurrentJob.perform_async(i)
  rescue Exception => e
    # RJ::Publisher.amqp_connection.stop
    puts e.message
    puts e.backtrace.join("\r\n")
    raise $!
  end
  i += 1
  sleep 1
end
